---
all:
  children:
    docker_hosts:
      hosts:
        docker-host:
          ansible_host: 10.0.0.10

    monitoring:
      hosts:
        monitoring-lxc:
          ansible_host: 10.0.0.20
          ansible_user: root
