---
all:
  children:
    edge:
      hosts:
        traefik-edge:
          ansible_host: 10.0.0.10
    apps:
      hosts: {}
    tools:
      hosts:
        adguard-dns:
          ansible_host: 10.2.0.11
          ansible_user: root
