---
all:
  children:
    edge:
      hosts:
        traefik-edge:
          ansible_host: 10.0.0.10
    apps:
      hosts:
        gitea-server:
          ansible_host: 10.2.0.12
          ansible_user: root
        cronmaster:
          ansible_host: 10.2.0.14
          ansible_user: root
    databases:
      hosts:
        percona-db:
          ansible_host: 10.2.0.13
          ansible_user: root
    tools:
      hosts:
        adguard-dns:
          ansible_host: 10.2.0.11
          ansible_user: root
        hermes-agent:
          ansible_host: 10.2.0.15
          ansible_user: root
