---
- name: Setup CronMaster
  hosts: cronmaster
  become: true

  pre_tasks:
    - name: Actualizar cache de APT
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: cronmaster_setup
